### ISSUE TITLE
Bad error when no activitylog entry found

### ISSUE THREAD

**Issue by vasichkin** [qubell/contrib-python-qubell-client#194]
When activity entry not found we got error:

```
13:16:26 [info] ======================================================================
13:16:26 [info] ERROR: test_workflows (stories.instance.test_activitylog.InstanceActivitylogTest)
13:16:26 [info] ----------------------------------------------------------------------
13:16:26 [info] Traceback (most recent call last):
13:16:26 [info]   File "/home/jenkins/workspace/ADP-Test-Pull/vermilion/tests/lime/stories/instance/test_activitylog.py", line 58, in test_workflows
13:16:26 [info]     eventually_assert()
13:16:26 [info]   File "/home/jenkins/workspace/ADP-Test-Pull/vermilion/tests/lime/client/qubell/api/tools/__init__.py", line 54, in f_retry
13:16:26 [info]     rv = f(*args, **kwargs)
13:16:26 [info]   File "/home/jenkins/workspace/ADP-Test-Pull/vermilion/tests/lime/stories/instance/test_activitylog.py", line 51, in eventually_assert
13:16:26 [info]     assert self.info.get_interval("workflow started: launch", "workflow finished: launch with status 'Succeeded'")
13:16:26 [info]   File "/home/jenkins/workspace/ADP-Test-Pull/vermilion/tests/lime/client/qubell/api/private/instance.py", line 604, in get_interval
13:16:26 [info]     interval = ActivityLog(self.log, self.severity, start=begin[0])
13:16:26 [info] TypeError: 'NoneType' object has no attribute '__getitem__'
```

Expected huma-readable error

**Comment by dmakhno** [comment]
Fixed in #196
